#!/bin/bash

ADDR=$1

if [ "X$ADDR" == "X" ];then
    echo $0 ip
    exit
fi

/data/open-c3-installer/tools/image-load.sh 

VERSION=$( cat /data/open-c3/installer.version | awk -F- '{print $1}' )

OPENC3VERSION=$VERSION /data/open-c3-installer/open-c3/open-c3.sh install $ADDR

echo Wait for the Open-C3 to start
sleep 60;

/data/open-c3/Installer/scripts/single/$VERSION.sh
/data/open-c3/open-c3.sh dup
/data/open-c3/open-c3.sh start
